{% set name = "sagemaker-tensorflow-serving-container" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e8cd251b11ad4f04899d5089c5c1189c55250c9e96ac54dac031584f77ace88b

build:
  number: 0
  script:
    - cp -r $SRC_DIR $SP_DIR/sagemaker_tensorflow_serving_container
  skip: true  # [win or py2k]

requirements:
  host:
    - python
  run:
    - python

test:
  imports:
    - sagemaker_tensorflow_serving_container

about:
  home: https://github.com/aws/sagemaker-tensorflow-serving-container
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SageMaker TensorFlow Serving Container is an a open source project that builds docker images for running TensorFlow Serving on Amazon SageMaker.
  doc_url: https://sagemaker.readthedocs.io/en/stable/using_tf.html
  dev_url: https://github.com/aws/sagemaker-tensorflow-serving-container

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - rluria14
